vich_uploader:
    db_driver: orm

    mappings:
        rtg_image:
            uri_prefix: /images/rtg
            upload_destination: '%kernel.project_dir%/public/images/rtg'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: false
            delete_on_remove: true