version: "3.1"
services:
    db:
      image: mariadb:10.0.38
      container_name: psemla_db
      volumes:
        - ./phpdocker/db/data:/var/lib/mysql
        - ./phpdocker/db/init/:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=app
        - MYSQL_USER=docker
        - MYSQL_PASSWORD=docker
      ports:
        - "8891:3306"
    webserver:
      image: nginx:alpine
      container_name: psemla_www
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8888:80"

    php-fpm:
      build: ./phpdocker/php
      container_name: psemla_php
      working_dir: /application
      volumes:
        - .:/application
